## Hi Pytorch

In [102]:
print("Hello! I am excited to learn Pytorch!")

Hello! I am excited to learn Pytorch!


https://www.learnpytorch.io/00_pytorch_fundamentals/

In [103]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors

Creating tensors

Pytorch tensor are created using `torch.tensor()` 

![alt text](source/SVMT.png)


https://docs.pytorch.org/docs/stable/tensors.html

In [104]:
# scalar
scalar = torch.tensor(7)
scalar # tensor(7)
scalar.ndim # 0

# scalar to python number
scalar.item() # 7

7

In [105]:
# vector
vector = torch.tensor([7, 7])
vector # tensor([7, 7])
vector.ndim # 1
vector.shape # torch.Size([2]) 

torch.Size([2])

In [106]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])
matrix # tensor([[ 7,  8],
       #         [ 9, 10]])
matrix.ndim # 2
matrix.shape # torch.Size([2, 2])

torch.Size([2, 2])

In [107]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]]])
tensor # tensor([[[1, 2, 3],
       #         [4, 5, 6], 
       #        [7, 8, 9]]])
    
tensor.ndim # 3
tensor.shape # torch.Size([1, 3, 3])
tensor[0] # tensor([[1, 2, 3],
          #         [4, 5, 6],
          #         [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random Tensors

Why Random Tensors?

Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ...`

In [108]:
# Creat a random tensor with torch.rand(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5008, 0.3888, 0.0124, 0.8628],
        [0.3599, 0.2453, 0.6099, 0.5081],
        [0.8279, 0.8372, 0.1819, 0.0204]])

In [109]:
# Create a random tensor with  similar shape to an image tensor 
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim # torch.Size([224, 224, 3])

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [110]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [111]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [112]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [113]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [114]:
# Use torch.range() and get deprecated message, use torch.arange() instead
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on the right device.

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [116]:
# Float 32 tensor 
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype is the data(e.g. float32 or float16), if None, it will be inferred by the data itself
                               device=None, # What device is the tensor on (e.g. "cpu" or "cuda"), if None, it will be the current device for the default tensor type (see torch.set_default_tensor_type())
                               requires_grad=False) # Whether or not to track gradients with this tensor (e.g. for autodifferentiation)

float_32_tensor

tensor([3., 6., 9.])

In [117]:
float_32_tensor.dtype

torch.float32

In [118]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [119]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [120]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [121]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`.
2. Tensor not right shape - to get shape from a tensor, can use `tensor shape`.
3. Tensor not on the right device - to get device from a tensor, can use `tensor.device`.

In [122]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6065, 0.6648, 0.3181, 0.1661],
        [0.0266, 0.4040, 0.0399, 0.4596],
        [0.0823, 0.8045, 0.9573, 0.8888]])

In [123]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [124]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of some_tensor: {some_tensor.dtype}")
print(f"Shape of some_tensor: {some_tensor.shape}")
print(f"Device some_tensor is on: {some_tensor.device}")

tensor([[0.6065, 0.6648, 0.3181, 0.1661],
        [0.0266, 0.4040, 0.0399, 0.4596],
        [0.0823, 0.8045, 0.9573, 0.8888]])
Datatype of some_tensor: torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device some_tensor is on: cpu


## Manipulation Tensors (tensor operations)

Tensor opertions include:
* Addition
* Substraction
* Multipilication(element-wise)
* Division
* Matrix Multipulication

In [125]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [126]:
# Multiplying tensors by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtracting tensors by 10
tensor - 10

tensor([-9, -8, -7])

In [128]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [129]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication.
   
![alt text](source/matrix-multiply-constant.svg)

2. Matrix multiplication (dot product).
   
![alt text](source/matrix-multiply-a.svg)

![alt text](source/matrix-multiply-c.svg)

More information on multiplying matrices. - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The *inner dimensions* must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the *outer dimensions*:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

In [130]:
# torch.matmul(torch.rand(3,2), torch.rand(3,2)) won't work because the inner dimensions don't match. 
torch.matmul(torch.rand(3,2), torch.rand(2,3)) # works because the inner dimensions match (2 and 2) and the output shape is determined by the outer dimensions (3 and 3) -> torch.Size([3, 3])

tensor([[0.6612, 0.8841, 0.6603],
        [0.5918, 0.7824, 0.5954],
        [0.0979, 0.1124, 0.1071]])

In [131]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [132]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [133]:
tensor

tensor([1, 2, 3])

In [134]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [135]:
tensor @ tensor

tensor(14)

In [136]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.45 ms, sys: 0 ns, total: 1.45 ms
Wall time: 1.21 ms


In [137]:
%%time 
torch.matmul(tensor, tensor)

CPU times: user 655 µs, sys: 0 ns, total: 655 µs
Wall time: 547 µs


tensor(14)

## One of the most common errors in deep learning: shape errors

In [138]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], 
                          [3, 4], 
                          [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm() is an alias for torch.matmul(). (It is an alias for writing less code.)
torch.matmul(tensor_A, tensor_B) # same as torch.mm() when both inputs are 2D tensors

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a giving tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed 
# because the inner dimensions match (2 and 2) 
# and the output shape is determined by the outer dimensions (3 and 3) -> torch.Size([3, 3])

print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape}(same shape as above), tensor_B.T: {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape} <- determined by the outer dimensions of the original shapes of tensor_A and tensor_B.T")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2])(same shape as above), tensor_B.T: torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3]) <- determined by the outer dimensions of the original shapes of tensor_A and tensor_B.T


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note:  torch.mean() only works on floating point tensors, 
# so we need to convert x to a float tensor first using .float() method.
# torch.mean(x) error
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()  

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max (argmin and argmax)

In [ ]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> 
# returns index position of the minimum value in x

x.argmin() # index of the minimum value in x

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax() -> 
# returns index position of the maximum value in x

x.argmax() # index of the maximum value in x

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - removes all `1` dimensions from a tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way.

### Reshape and view

**Note:**
Reshape may copy or rearrange data to fit a new shape, while view returns a new tensor sharing the same memory and requires the tensor to be contiguous.


In [154]:
# Let's create a tensor
import torch
x = torch.arange(24.)
x, x.shape

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]),
 torch.Size([24]))

In [155]:
# Add an extra dimension
x_reshaped = x.reshape(1, 24)    
x_reshaped, x_reshaped.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]]),
 torch.Size([1, 24]))

In [156]:
# Add 3D dimension
x_reshaped_3d = x.reshape(2, 3, 4)
x_reshaped_3d, x_reshaped_3d.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 torch.Size([2, 3, 4]))

In [157]:
# Change the view
z = x.view(1, 24)
z, z.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]]),
 torch.Size([1, 24]))

In [158]:
# Changing z changes x 
# (because a view of a tensor shares the same memory as the original input)

z[:, 0] = 5
z, x

(tensor([[ 5.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]]),
 tensor([ 5.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]))

### Stack

dim tells which layer the stacked tensors go into.

In [218]:
x = torch.arange(6.)
x, x.shape

(tensor([0., 1., 2., 3., 4., 5.]), torch.Size([6]))

In [219]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
print(f"x_stacked while dim = 0: \n {x_stacked}")
print(f"x_stacked.shape: {x_stacked.shape} \n")
x_stacked_dim1 = torch.stack([x, x, x, x], dim=1) 
print(f"x_stacked while dim = 1: \n {x_stacked_dim1}")
print(f"x_stacked_dim1.shape: {x_stacked_dim1.shape} \n")

x_stacked while dim = 0: 
 tensor([[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]])
x_stacked.shape: torch.Size([4, 6]) 

x_stacked while dim = 1: 
 tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]])
x_stacked_dim1.shape: torch.Size([6, 4]) 



In [220]:
x = torch.tensor([[1, 2],
                  [3, 4]])  # shape = [2, 2]
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[[1, 2],
          [1, 2],
          [1, 2]],
 
         [[3, 4],
          [3, 4],
          [3, 4]]]),
 torch.Size([2, 3, 2]))

### Squeeze && UnSqueeze

**Squeeze:** removes all single dimensions from a target tensor.

**Unsqueeze:** adds a single dimension to a target tensor at a specific dim(dimension).

In [221]:
x = torch.arange(1., 7.)
x_reshaped = x.reshape(1, 6)
print(f"Previous tensor: \n {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape} \n")

#Remove all the extra dimensions with squeeze()
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: \n {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: 
 tensor([[1., 2., 3., 4., 5., 6.]])
Previous shape: torch.Size([1, 6]) 

New tensor: 
 tensor([1., 2., 3., 4., 5., 6.])
New shape: torch.Size([6])


In [222]:
# torch.unsqueeze() adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous tensor: \n {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape} \n")

# Add an extra dimension with unsqueeze() to the end of the shape
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: \n {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: 
 tensor([1., 2., 3., 4., 5., 6.])
Previous shape: torch.Size([6]) 

New tensor: 
 tensor([[1., 2., 3., 4., 5., 6.]])
New shape: torch.Size([1, 6])


### Permute

Returns a view of the original tensor `input` with its dimensions permuted.

In [228]:
# torch.permute() rearranges the dimensions of a target tensor 
# in a specified order and returns a view of the original tensor 
# with the same data but different shape.

x_original = torch.rand(size=(224, 224, 3)) # height, width, color channels

# Permute the original tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift axis 0 to 1, axis 1 to 2, axis 2 to 0

print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [229]:
x_original[0,0,0]

tensor(0.5118)

## Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [230]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [231]:
# Let's index on our new tensor
x[0] # get the first (and only) item on the 0th axis

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [233]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [235]:
#Let's index on the most inner bracket (dim = 2)
x[0][1][1]

tensor(5)

In [240]:
# You can also use ":" to select "all" of the target dimension
print(f"{x[:, 0]}") 

# Get the value of 0th and 1st dimensions but only index 1 of 2nd dimension
print(f"{x[:,:, 1]}")

# Get all values of the 0th dimension but only index 1 of 1st and 2nd dimensions
print(f"{x[:, 1, 1]}")

# Get index 0 of 0th and 1st dimensions but all values of 2nd dimension
print(f"{x[0, 0, :]}")

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


In [ ]:
# Index on x to return 9
# Note: 
# Indexing with integers returns a scalar (removes dimensions), 
# while slicing (:) returns a vector (preserves dimensions).
print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2 ])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensor & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `Torch.Tensor.Numpy()`



In [ ]:
# NumPy array to Pytorch tensor
import numpy as np
import torch

array = np.arange(1.0, 8.0)
# tensor = torch.from_numpy(array, type = torch.float32) error
# tensor = torch.from_numpy(array).type(torch.float32) right

tensor = torch.from_numpy(array)
# warning: when converting from numpy -> pytorch, 
# pytorch reflects numpy's default datatype of float64 
# unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [266]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [268]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [269]:
# Change the tensor, what will this do to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [275]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Random tensor A: \n {random_tensor_A} \n")
print(f"Random tensor B: \n {random_tensor_B} \n")
print(random_tensor_A == random_tensor_B)

Random tensor A: 
 tensor([[0.3553, 0.3343, 0.7613, 0.0080],
        [0.5894, 0.6443, 0.2704, 0.4856],
        [0.8604, 0.1762, 0.9422, 0.6806]]) 

Random tensor B: 
 tensor([[0.2776, 0.9381, 0.3204, 0.3084],
        [0.1276, 0.8886, 0.6687, 0.0187],
        [0.3844, 0.1147, 0.6789, 0.5319]]) 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [277]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) 
random_tensor_D = torch.rand(3, 4)

print(f"Random tensor C: \n {random_tensor_C} \n")
print(f"Random tensor D: \n {random_tensor_D} \n")

print(random_tensor_C == random_tensor_D)

Random tensor C: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

Random tensor D: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resource for reproducibility:
* https://en.wikipedia.org/wiki/Random_seed
* https://docs.pytorch.ac.cn/docs/stable/notes/randomness.html

## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers,
thanks to CUDA + NVDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well).
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation:

https://pytorch.org/get-started/locally/

In [2]:
!nvidia-smi

Thu Mar 19 16:39:38 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P0             28W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

For PyTorch since it's capable of running computer on the GPU or CPU it's best practice to setup device agnostic code:

https://docs.pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [4]:
import torch
# Check for GPU access with PyTorch
if torch.cuda.is_available():
    print("GPU is available")

GPU is available


In [7]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [6]:
# Count number of devices
torch.cuda.device_count()

1

## 

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [8]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# Move tensor to the GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [10]:
# if tensor is on GPU, move can't transform it to NumPy
tensor_on_gpu.numpy() # error

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
# To fix the GPU tensor to NumPy error, 
# we need to move the tensor back to the CPU first 
# before converting it to a NumPy array
tensor_on_cpu = tensor_on_gpu.to("cpu").numpy()
tensor_on_cpu

array([1, 2, 3])

In [12]:
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

## Exercises & Extra-curriculum

See exercises for this notebook here: 

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [14]:
import torch

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on **torch.Tensor** and for **torch.cuda**.

In [13]:
# Create a random tensor with shape (7, 7).
random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.6746, 0.8955, 0.6953, 0.5792, 0.2154, 0.1362, 0.9430],
        [0.1087, 0.1256, 0.6661, 0.0609, 0.9685, 0.1325, 0.6108],
        [0.1062, 0.8259, 0.5912, 0.2168, 0.6976, 0.7263, 0.7667],
        [0.9552, 0.6822, 0.6987, 0.9458, 0.0534, 0.5598, 0.6433],
        [0.1238, 0.5597, 0.1239, 0.9107, 0.0665, 0.6905, 0.2897],
        [0.6539, 0.6974, 0.6796, 0.7839, 0.2962, 0.6256, 0.0883],
        [0.7017, 0.7329, 0.2663, 0.1332, 0.4508, 0.5706, 0.3593]])
